generate SW injector
flipkart-incubator/Service-Worker-Tools pull request #3
Opened 2018-06-11 09:59 UTC by aroramayur

2018-06-11 10:01 UTC, aroramayur commented
@shubh54 Need you help with styling the iFrame ( they way it looks in Hermes ). We should look at separating out CSS . With a CSP not allowing inline styles , this would not work. 
Update handler call back should be optional. One could either use the injector or use the util method and provide a callback.

2018-06-12 14:24 UTC, shubh54 requested changes

2018-06-12 14:24 UTC, shubh54 commented on src/helpers/injector.js
> +        updateApp.style.color = '#fff';
Object.assign(updateApp.style, {additional styles}),
same can be done for updateText.style

Advantage -> More readable code and cleaner.

2018-06-12 14:24 UTC, shubh54 commented on src/helpers/injector.js
> +const iframeStyles = () => 'position: fixed;top: 0;width: 410px;padding:5px;height: 110px;left: 50%;transform: translate(-50%);background-color:#f0f5ea;box-shadow:0 0 1px rgba(94,164,0,.9);font-size:
lets take iframeStyles from user and override defaults. Like merge(iframeDefaultStyles, userProvidedStyles)

Can be picked up later.

2018-06-21 18:26 UTC, shubh54 requested changes

2018-06-21 18:26 UTC, shubh54 commented on src/helpers/injector.js
> +    window.location.reload();
only window.location reload won't suffice. earlier implementation reloaded all tabs that were open so that only a single service worker instance is running across all tabs.

2018-06-22 06:14 UTC, shubh54 approved these changes

2018-06-22 06:14 UTC, merged